Bookers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#root'
  get '/home/about' => 'homes#about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follows', as: 'follows'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post '/follow/:id' => 'relationships#create', as: 'follow'
  delete '/unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get '/search' => 'search#search', as: 'search'

  resources :books, except: :new do
  	resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships #フォロー取得
  has_many :followings, through: :relationships, source: :follow #自分がフォローしている人
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id' #フォロワー取得
  has_many :followers, through: :reverse_of_relationships, source: :user #自分をフォローしている人

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
  	@user = current_user
    @new_book = Book.new
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @new_book = Book.new
  	@books = Book.where(user_id: params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have update user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:user_id])
    @users = @user.followings
    render :follows
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
    render :followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/users/_index.html.erb
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="4"></th>
			</tr>
		</thead>
		<tbody>
			<% users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
				<td><%= user.name %></td>
				<td>フォロー数：<%= user.followings.count %></td>
				<td>フォロワー数：<%= user.followers.count %></td>
				<td>
					<% unless current_user == user %>
					<% if current_user.following?(user) %>
						<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
					<% else %>
						<%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
					<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user_path(user.id) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

Bookers/app/views/users/_sidebar.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
	<table class="table">
		<tr></tr>
		<tr>
			<th>name</th>
			<td><%= user.name %></td>
		</tr>
		<tr>
			<th>introduction</th>
			<td><%= user.introduction %></td>
		</tr>
		<tr>
			<th>follows</th>
			<td><%= link_to user.followings.count, user_follows_path(user) %></td>
		</tr>
		<tr>
			<th>followers</th>
			<td><%= link_to user.followers.count, user_followers_path(user) %></td>
		</tr>
	</table>
	<div class="actions row">
		<% unless current_user == user %>
			<% if current_user.following?(user) %>
				<%= link_to 'フォロー外す', user_relationships_path(user), method: :delete, class: "col-xs-12 btn btn-primary" %>
			<% else %>
				<%= link_to 'フォローする', user_relationships_path(user), method: :post, class: "col-xs-12 btn btn-success" %>
			<% end %>
		<% else %>
			<%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
		<% end %>
	</div>

	<h2>New book</h2>

	<% if new_book.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= new_book.errors.count %> errors prohibited this obj from being saved:</h2>
	    <ul>
	    <% new_book.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= form_for(new_book, url:'/books') do |f| %>
		<div class="field row">
			<label for="book_title">Title</label>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>
		<div class="field row">
			<label for="book_opinion">Opinion</label>
			<%= f.text_area :body, class: "col-xs-12 book_opinion" %>
		</div>
		<div class="actions row">
			<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
		</div>
	<% end %>
</div>

Bookers/app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
    <div class="field">
        <label>Name</label>
        <%= f.text_field :name, autofocus: true, placeholder:"", class: "name" %>
    </div>
    <div class="field">
        <label>Image</label>
        <%= f.attachment_field :profile_image, class: "image" %>
    </div>
    <div class="field">
        <label>Introduction</label>
        <%= f.text_area :introduction, autofocus: true, placeholder:"", class: "introduction" %>
    </div>
    <div class="actions">
        <%= f.submit "Update User" %>
    </div>
<% end %>

Bookers/app/views/users/index.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Users</h2>
<%= render partial: 'users/index', locals: {users: @users} %>
</div>

Bookers/app/views/users/show.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>

<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>&nbsp;</th>
				<th>Title</th>
				<th>Opinion</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td><%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.body %></td>
				<td>コメント数：<%= book.book_comments.count %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>