Bookers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#root'
  get '/home/about' => 'homes#about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follows', as: 'follows'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post '/follow/:id' => 'relationships#create', as: 'follow'
  delete '/unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get '/search' => 'search#search', as: 'search'

  resources :books, except: :new do
  	resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@new_book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
  	@user = current_user
    @new_book = Book.new
  	@books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    #user.id == @book.user_id
  	@user = User.find_by(id: @book.user_id)
    @new_book = Book.new
    @comment = BookComment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "You have update book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user_id == current_user.id
  end
end

Bookers/app/helpers/book_helper.rb
module BookHelper
end

Bookers/app/views/books/_index.html.erb
<table  class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
			<% books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user_id) do %>
						<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
					<% end %>
					</td>
				<td><%= link_to book.title, book_path(book.id) %></td>
				<td><%= book.body %></td>
				<td>
				<% if book.favorited_by?(current_user) %>
					<%= link_to book_favorites_path(book), method: :delete do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					<%= book.favorites.count %>
					<% end %>
				<% else %>
					<%= link_to book_favorites_path(book), method: :post do %>
					<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					<%= book.favorites.count %>
					<% end %>
				<% end %>
				</td>
				<td>
					コメント数：<%= book.book_comments.count %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>

Bookers/app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>

			<% if @book.errors.any? %>
			  <div id="error_explanation">
			    <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
			    <ul>
			    <% @book.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>

			<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
				<div class="field row">
					<label for="book_title">Title</label>
					<%= f.text_field :title, class: "book_title col-xs-12" %>
				</div>
				<div class="field row">
					<label for="book_opinion">Opinion</label>
					<%= f.text_area :body, class: "book_opinion col-xs-12" %>
				</div>
				<div class="action row">
				<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>
			<%= link_to "Show", book_path(@book.id) %>
			|
			<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

Bookers/app/views/books/index.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Books</h2>
	<%= render '/books/index', books: @books %>
</div>

Bookers/app/views/books/show.html.erb
<%= render partial: 'users/sidebar', locals: {user:@user, new_book:@new_book} %>
<div class="col-xs-9">
	<h2>Book detail</h2>

	<table class="table">
		<td>
			<%= link_to user_path(@user.id) do %>
				<%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br>
				<%= @user.name %>
			<% end %>
		</td>
		<td><%= link_to @book.title, @book %></td>
		<td><%= @book.body %></td>

		<td>
			<% if @book.favorited_by?(current_user) %>
				<%= link_to book_favorites_path(@book), method: :delete do %>
				<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
				<%= @book.favorites.count %>
				<% end %>
			<% else %>
				<%= link_to book_favorites_path(@book), method: :post do %>
				<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
				<%= @book.favorites.count %>
				<% end %>
			<% end %>
		</td>

		<td>コメント数：<%= @book.book_comments.count %></td>

		<% if @book.user == current_user %>
		<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
		<td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" , class: "btn btn-danger btn-sm" %></td>
		<% end %>
	</table>
	<% @book.book_comments.each do |book_comment| %>
		<table>
			<tr>
				<td>
					<%= link_to user_path(book_comment.user_id) do %>
					<%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br>
					<%= book_comment.user.name %>
					<% end %>
				</td>
				<td><%= book_comment.comment %></td>
				<td>
					<% if book_comment.user == current_user %>
						<%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, class: "btn btn-danger btn-sm" %>
					<% end %>
				</td>
			</tr>
		</table>
	<% end %>
	<div class="row">
	<%= form_for [@book, @comment] do |f| %>
		<div class="field col-xs-10">
			<%= f.text_area :comment, class: "col-xs-12 comment-field" %>
		</div>
		<div class="action col-xs-2">
			<%= f.submit "送信", class: "comment-submit" %>
		</div>
	</div>
	<% end %>
</div>