Bookers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#root'
  get '/home/about' => 'homes#about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follows', as: 'follows'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post '/follow/:id' => 'relationships#create', as: 'follow'
  delete '/unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get '/search' => 'search#search', as: 'search'

  resources :books, except: :new do
  	resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

Bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

Bookers/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

Bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships #フォロー取得
  has_many :followings, through: :relationships, source: :follow #自分がフォローしている人
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id' #フォロワー取得
  has_many :followers, through: :reverse_of_relationships, source: :user #自分をフォローしている人

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, :except=>[:root, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception

	private

	def after_sign_up_path_for(resource)
      user_path(resource)
  	end
  	def after_sign_in_path_for(resource)
	  user_path(resource)
	end
	def after_sign_out_path_for(resource)
	  root_path
	end

	#protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@new_book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
  	@user = current_user
    @new_book = Book.new
  	@books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    #user.id == @book.user_id
  	@user = User.find_by(id: @book.user_id)
    @new_book = Book.new
    @comment = BookComment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "You have update book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user_id == current_user.id
  end
end

Bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id:book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def root
  end

  def about
  end

end

Bookers/app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@search = params[:search]
		@options = params[:option]
		@ways = params[:way]

		if @options == "user"
			if @ways == "perfect"
				@users = User.where(name: "#{@search}")
			end
			if @ways == "front"
				@users = User.where('name LIKE ?', "#{@search}%")
			end
			if @ways == "behind"
				@users = User.where('name LIKE ?', "%#{@search}")
			end
			if @ways == "part"
				@users = User.where('name LIKE ?', "%#{@search}%")
			end
		end

		if @options == "book"
			if @ways == "perfect"
				@books = Book.where(body: "#{@search}")
			end
			if @ways == "front"
				@books = Book.where('body LIKE ?', "#{@search}%")
			end
			if @ways == "behind"
				@books = Book.where('body LIKE ?', "%#{@search}")
			end
			if @ways == "part"
				@books = Book.where('body LIKE ?', "%#{@search}%")
			end
		end
	end

end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
  	@user = current_user
    @new_book = Book.new
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @new_book = Book.new
  	@books = Book.where(user_id: params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have update user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:user_id])
    @users = @user.followings
    render :follows
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
    render :followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers/app/helpers/book_helper.rb
module BookHelper
end

Bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Bookers/app/helpers/search_helper.rb
module SearchHelper
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-header navbar-left">
          <h4 class="header-logo">Bookers</h4>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                logout
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to "/users/sign_up" do %>
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                  sign up
                <% end %>
              </li>
              <li>
                <%= link_to "/users/sign_in" do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                  login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <div class="main container">
      <div class="row">
        <% if flash[:notice] %>
          <div>
            <%= flash[:notice] %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-xs-5 col-xs-offset-4">
          <% if user_signed_in? %>
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :search %>
            <%= select_tag(:option, options_for_select([["User","user"],["Book","book"]])) %>
            <%= select_tag(:way, options_for_select([["完全一致","perfect"],["前方一致","front"],["後方一致","behind"],["部分一致","part"]])) %>
            <%= submit_tag "検索" %>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>